# docker-compose.orderservice.yml

services:
  orderservice:
    container_name: orderservice
    build:
      context: .                 
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8081
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "8081:8081"
    # depends_on:
    #   kafka:
    #     condition: service_started
    networks:
      - eda_net    

networks:
  eda_net:
    external: true
    name: eda-net 



