# docker-compose.orderservice.yml

services:
  orderservice:
    image: ofekcofman98/eda-orderservice:latest
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8081
      - Kafka__BootstrapServers=kafka:9092
    ports:
      - "8081:8081"
    networks:
      - eda_net    

networks:
  eda_net:
    external: true
    name: eda-net 



